#logging:
#  level:
#    root: debug

spring:
  application:
    name: 'pas-kafka'

  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:29092}
    producer:
      value-serializer: 'org.springframework.kafka.support.serializer.JsonSerializer'
    consumer:
      value-deserializer: 'org.springframework.kafka.support.serializer.JsonDeserializer'
      properties:
        spring.json.trusted.packages: "com.demo.paskafka.*"
      group-id: 'pas-kafka'
